server:
  port: 8081

spring:
  application:
    name: spring-client

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-client
            client-secret: 2aF1lqlk5QQnqD4qO7pK6Devx3gadynz
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/sp-realm

logging:
  level:
    org.springframework.security: DEBUG
