server:
  port: 8082

spring:
  application:
    name: spring-resource-server

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sp-realm

logging:
  level:
    org.springframework.security: DEBUG
